# ==============================================================================
# Custom helper functions for `slingshot`.
# ==============================================================================


#' Run `slingshot` on a Seurat object
#'
#' @param srat Seurat object
#' @param reduction Dimensional reduction to use for `slingshot` pseudotime
#'   (either "pca" or "umap")
#' @param cluster_labels Vector of cluster labels for each cell, or name of the
#'   metadata column with the cluster labels
#' @param start_cluster Name of the lineage start cluster
#' @param num_pcs Number of principal components (PCs) to use when inferring
#'   pseudotime; only if reduction is not "umap" (e.g., "pca"). If `num_pcs` is
#'   greater than the number of PCs present, then all PCs will be used.
#' 
#' @return PseudotimeOrdering object generated by `slingshot`
#' 
run_slingshot <- function(
  srat,
  reduction,
  cluster_labels,
  start_cluster = NULL,
  num_pcs = if (reduction != "umap") 50 else NULL
) {
  message(sprintf("Running slingshot on the %s reduction", reduction))
  if (length(cluster_labels) == 1) {
    message(sprintf("Using the %s metadata column for cluster assignment", 
                    cluster_labels))
  }
  
  # get embeddings
  embeds <- Embeddings(srat, reduction = reduction)
  
  # subset embeddings for PCA
  if (reduction == "pca") {
    if(num_pcs < ncol(embeds)) {
      embeds <- embeds[, 1:num_pcs]
    }
    message(sprintf("Using the top %s principal components", ncol(embeds)))
  }
  
  # slingshot
  pto <- slingshot(
    data = embeds,
    clusterLabels = 
      if (length(cluster_labels) == 1) {
        srat@meta.data[[cluster_labels]]
      } else {
        cluster_labels
      },
    start.clus = start_cluster
  )
  
  return(pto)
}


#' Plot `slingshot` results with `ggplot2`.
#'
#' @param pto PseudotimeOrdering object (or SlingshotDataSet object)
#' @param colour_by Have the cells coloured by cluster labels ("`cluster`") or
#'   by pseudotime ("`pseudotime`"). If using "`pseudotime`", a list of
#'   `ggplot2` plots will be returned, one for each of the pseudotime lineages.
#'
#' @return `ggplot2` object or list of `ggplot2` objects
#'   
plot_slingshot <- function(
  pto,
  colour_by = c("cluster", "pseudotime")
) {
  # convert to SlingshotDataSet object for plotting
  sds <- as.SlingshotDataSet(pto)
  
  # extract cell embeddings
  embeds <- slingReducedDim(sds)[, 1:2] %>% as.data.frame(.)
  
  # extract pseudotime
  pseudotime <- slingPseudotime(sds) %>% as.data.frame(.)
  
  # extract cluster labels
  cluster_labels <- slingClusterLabels(sds) %>% 
    as_tibble(rownames = "cell_id") %>% 
    pivot_longer(!cell_id, names_to = "cluster", values_to = "binary") %>% 
    filter(binary == 1) %>% 
    column_to_rownames(var = "cell_id") %>% 
    select(!binary)
  
  # extract lineage curves
  curves <- slingCurves(sds, as.df = TRUE)
  
  
  # combine embeddings, pseudotime, cluster labels into single object
  embeds <- base::merge(embeds, pseudotime, by = "row.names", all = TRUE) %>% 
    `row.names<-`(.$Row.names) %>% 
    select(!Row.names)
  embeds$cluster_labels <- cluster_labels[row.names(embeds), ] %>% 
    factor(., levels = unique(str_sort(., numeric = TRUE)))
  
  # get x and y for plotting
  x <- colnames(embeds)[1]
  y <- colnames(embeds)[2]
  
  if (colour_by == "cluster") {
    
    # colour cells by cluster
    plt <- ggplot(data = embeds, mapping = aes(x = .data[[x]], y = .data[[y]])) + 
      geom_point(mapping = aes(colour = embeds[, "cluster_labels"]), size = 0.5) + 
      geom_path(
        data = curves %>% arrange(Order),
        mapping = aes(x = .data[[x]], y = .data[[y]], group = Lineage)
      ) + 
      labs(
        x = colnames(embeds)[1],
        y = colnames(embeds)[2],
        colour = "cluster_labels"
      ) + 
      theme_classic()
    
  } else if (colour_by == "pseudotime") {
    
    # colour cells by pseudotime
    
    # get all the lineages
    lineages <- str_subset(colnames(embeds), "^Lineage")
    
    # save all plots to list
    plt <- list()
    
    for (i in 1:length(lineages)) {
      
      p <- ggplot(data = embeds, mapping = aes(x = .data[[x]], y = .data[[y]])) + 
        geom_point(mapping = aes(colour = .data[[lineages[i]]]), size = 0.5) + 
        geom_path(
          data = curves[curves$Lineage == i, ] %>% arrange(Order),
          mapping = aes(x = .data[[x]], y = .data[[y]], group = Lineage)
        ) + 
        labs(
          title = lineages[i],
          x = colnames(embeds)[1],
          y = colnames(embeds)[2],
          colour = "pseudotime"
        ) + 
        theme_classic()
      
      plt[[lineages[i]]] <- p
    }
    
  } else {
    stop("`colour_by` must be one of c(\"cluster\", \"pseudotime\")")
  }
  
  return(plt)
}


#' Calculate weighted average pseudotimes of multiple lineages.
#'
#' Adapted from the original `slingAvgPseudotime` function in the `slingshot`
#' package since this function appears to be missing from the current package
#' version. Unable to update via Bioconductor because it requires R 4.2,
#' currently only running R 4.1.
#'
#' @param pto PseudotimeOrdering object
#'
#' @return Vector of average pseudotimes weighted by lineage assignment weights.
#'   
mean_pseudotime <- function(
  pto
) {
  return(rowSums(
    slingPseudotime(pto, na = FALSE) * slingCurveWeights(pto, as.probs = TRUE)
  ))
}
