---
title: "Integration of RL lineage cells"
---

Code for UMAPs of the RL lineage integration. Note that the code chunks are run interactively using the `scrnaseq_env` conda environment. This file was **not** rendered with `quarto render`.

## Initialization

Packages:

```{r}
library(tidyverse)
library(patchwork)
library(Seurat)
```

Functions/files/directories:

```{r}
thesis_dir <- "../../"
source(file.path(thesis_dir, "./utils.R"))
source(file.path(thesis_dir, "../software/utilities/cell_labelling.R"))
source(file.path(thesis_dir, "../software/utilities/plotting.R"))

out_dir <- "./integ_rl"
my_pals <- get_custom_pals()
```


## UMAPs of integrated RL lineage cells

```{r}
# load Seurat object for integrated dataset
srat_qs <- get_srat_paths()
integ_srat <- load_srat(srat_qs["rl"]) %>%
  pluck("rl")
```

```{r}
# get cell type annotations (from `cell_labelling.R`)
integ_srat <- label_rl_lineage_integration(integ_srat)

# collapse UBC subclusters into one cluster
integ_srat@meta.data <- mutate(
  integ_srat[[]],
  broad_annot = case_when(
    str_starts(cell_type_annot, "UBC") ~ "UBC",
    .default = cell_type_annot
  )
)

# set column for clusters
rl_cluster <- "snn_res.0.4"
```

```{r}
# UMAP coloured by species
.plt1 <- DimPlot(
  integ_srat,
  reduction = "umap",
  cells.highlight = WhichCells(integ_srat, expression = species == "human"),
  sizes.highlight = 0.01,
  label = FALSE
) + 
  labs(title = NULL) + 
  scale_colour_manual(
    labels = c("mouse", "human"),
    values = my_pals$species,
    guide = guide_legend(override.aes = list(size = 3), nrow = 1)
  ) + 
  theme_classic2() + 
  theme(
    legend.position = "inside",
    legend.position.inside = c(0.01, 1),
    legend.justification.inside = c(0, 1)
  )
ggsave(
  filename = "integ_rl_species.png",
  plot = .plt1,
  path = out_dir,
  width = 5,
  height = 5,
  units = "in",
  dpi = 600
)

# UMAPs coloured by cluster and cell type
.plt_list <- map(
  .x = c("broad_annot", rl_cluster),
  .f = \(group_by) {
    if (str_detect(group_by, "snn_res")) {
      cols <- my_pals$rl_integ_clust
      filename <- "integ_rl_cluster.png"
    } else if (group_by == "broad_annot") {
      cols <- my_pals$rl_integ_annot
      filename <- "integ_rl_broad_annot.png"
    }

    .plt <- DimPlot(
      integ_srat,
      reduction = "umap",
      group.by = group_by,
      cols = cols,
      label = TRUE,
      label.size = 3,
      repel = TRUE
    ) + 
      labs(title = NULL) + 
      guides(colour = guide_legend(
        override.aes = list(size = 3),
        nrow = 3
      )) + 
      theme_classic2() + 
      theme(legend.position = "bottom")

    # hacky way of setting the seed for the UMAP labels
    .plt[[1]]$layers[[2]]$geom_params$seed <- 42

    ggsave(
      filename = filename,
      plot = .plt,
      path = out_dir,
      width = 5,
      height = 5.5,
      units = "in",
      dpi = 600
    )

    return(.plt)
  }
)

rl_umaps <- c(.plt_list, list(.plt1))
```


## Bar plots

```{r}
# distribution of cells from each dataset in each cluster

# get dataset for plotting
integ_srat@meta.data <- integ_srat[[]] %>%
  mutate(dataset = case_when(
    str_detect(dataset_name, "Aldinger") ~ "Aldinger (human)",
    str_detect(dataset_name, "Sepp(.*)human") ~ "Sepp (human)",
    str_detect(dataset_name, "Sepp(.*)mouse") ~ "Sepp (mouse)",
    str_detect(dataset_name, "Vladoiu") ~ "Vladoiu (mouse)"
  ))

# bar plot
dataset_cluster_bar <- cluster_barplot(
  object = integ_srat,
  split.by = "dataset",
  group.by = rl_cluster
) + 
  labs(x = "cluster") + 
  theme_classic2() + 
  theme(
    legend.position = "inside",
    legend.position.inside = c(0.95, 0.95),
    legend.justification.inside = c(1, 1)
  )
ggsave(
  filename = "dataset_cluster_bar.png",
  plot = dataset_cluster_bar,
  path = out_dir,
  width = 7.5,
  height = 5,
  units = "in",
  dpi = 600
)
```


## Final figure

```{r}
.plt <- wrap_plots(
  c(rl_umaps, list(free(dataset_cluster_bar))),
  ncol = 2
) + 
  plot_annotation(
    title = "Human + mouse integrated rhombic lip lineage",
    tag_levels = "A",
    theme = theme(
      plot.title = element_text(hjust = 0.5, size = rel(1.5))
    )
  )
walk(
  .x = c("png", "pdf"),
  .f = \(device) {
    ggsave(
      filename = paste("final", device, sep = "."),
      plot = .plt,
      path = out_dir,
      width = 9,
      height = 8,
      units = "in",
      dpi = 600
    )
  }
)
```
