---
title: Check if BRCA1 mutations in MB affect splicing
date: 2025-02-26
metadata-files: 
  - _metadata.yml
  - ../_quarto.yml
---

## Goal of this analysis

To determine if the BRCA1 mutations present in medulloblastoma have an effect on splicing. [SpliceAI](https://github.com/Illumina/SpliceAI) (in the Variant Effect Predictor tool) was used to predict if the mutations affect the splice sites.


## Files and directories

### Code

The code can be found in `<tumour software directory>/ICGC/prep_for_vep.R`. All code was run using the `scrnaseq_env` conda environment.

Briefly, this script reads in the mutations from the ICGC files, filters for those that overlap the BRCA1 gene, and saves the output to `BRCA1_vep_input.txt`. This file is then used as input for the Ensembl Variant Effect Predictor (VEP).

### Output

The output can be found in `<tumour results directory>/ICGC/20250226/`.


## Results

The script's output `.txt` file was uploaded to [VEP](https://grch37.ensembl.org/info/docs/tools/vep/index.html). All settings were left as default except for the SpliceAI tool which was set to "Enabled" and "Masked scores". The equivalent command line function can be found below (as reported by the tool):

```bash
./vep --af --appris --biotype --buffer_size 500 --check_existing --distance 5000 --mane --plugin SpliceAI,snv=[path_to]/spliceai_scores.masked.snv.hg19.vcf.gz,indel=[path_to]/spliceai_scores.masked.indel.hg19.vcf.gz --polyphen b --pubmed --regulatory --show_ref_allele --sift b --species homo_sapiens --symbol --transcript_version --tsl --uploaded_allele --cache --input_file [input_data] --output_file [output_file] --port 3337
```

The results were saved to `BRCA1_vep_results.txt/.pdf`. All variants had SpliceAI scores of 0, indicating that **none of the *BRCA1* mutations affected splicing**. As suggested by Ander, a known mutation in *NOTCH1* that affects splicing was included as a positive control (see [PMID 26200345, fig 2](https://www.nature.com/articles/nature14666)). This variant returned a SpliceAI splice acceptor gain score of 0.72, indicating that the mutation likely turned it into a splice acceptor site and suggesting that SpliceAI was working as expected.

### Clean up output results for supplementary table

```{r}
#| cache: false
#| cache-lazy: false

library(tidyverse)

# load file
vep_df <- read_tsv(
  "/.mounts/labs/pailab/private/icheong/CBL_scRNAseq/results/tumour/ICGC/20250226/BRCA1_vep_results.txt"
) %>%
  rename_with(\(x) {str_remove(string = x, pattern = "#")}, 1)

# filter columns
vep_df <- select(
  vep_df,
  Uploaded_variation,
  Location,
  UPLOADED_ALLELE,
  contains("SpliceAI") & !contains("SYMBOL")
) %>%
  # keep unique rows
  distinct() %>%
  filter(!str_starts(string = Uploaded_variation, pattern = "9_")) %>%
  rename(Allele = "UPLOADED_ALLELE")

# save output
write_tsv(
  x = vep_df,
  file = "/.mounts/labs/pailab/private/icheong/CBL_scRNAseq/results/tumour/ICGC/20250226/BRCA1_SpliceAI_supplementary.tsv"
)
```
